[2025-03-17T00:17:57.306+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T00:17:57.359+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_reviews_pipeline.dbt_run scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2025-03-17T00:17:57.377+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_reviews_pipeline.dbt_run scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2025-03-17T00:17:57.377+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-17T00:17:57.412+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2024-04-02 00:00:00+00:00
[2025-03-17T00:17:57.430+0000] {standard_task_runner.py:72} INFO - Started process 251644 to run task
[2025-03-17T00:17:57.443+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_reviews_pipeline', 'dbt_run', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpozn67wm6']
[2025-03-17T00:17:57.445+0000] {standard_task_runner.py:105} INFO - Job 169: Subtask dbt_run
[2025-03-17T00:17:57.631+0000] {task_command.py:467} INFO - Running <TaskInstance: load_reviews_pipeline.dbt_run scheduled__2024-04-02T00:00:00+00:00 [running]> on host DESKTOP-IM7V4RI.
[2025-03-17T00:17:58.030+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='load_reviews_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2025-03-17T00:17:58.033+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T00:17:58.035+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T00:17:58.036+0000] {logging_mixin.py:190} INFO - Current task name:dbt_run state:running start_date:2025-03-17 00:17:57.359755+00:00
[2025-03-17T00:17:58.039+0000] {logging_mixin.py:190} INFO - Dag name:load_reviews_pipeline and current dag run status:running
[2025-03-17T00:17:58.040+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T00:17:58.042+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-17T00:17:58.045+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/mohammed/.dbt/bank_reviews_project && dbt run']
[2025-03-17T00:17:58.082+0000] {subprocess.py:99} INFO - Output:
[2025-03-17T00:18:08.758+0000] {subprocess.py:106} INFO - [0m00:18:08  Running with dbt=1.9.3
[2025-03-17T00:18:11.799+0000] {subprocess.py:106} INFO - [0m00:18:11  Registered adapter: postgres=1.9.0
[2025-03-17T00:18:16.508+0000] {subprocess.py:106} INFO - [0m00:18:16  Found 6 models, 4 data tests, 2 sources, 433 macros
[2025-03-17T00:18:16.551+0000] {subprocess.py:106} INFO - [0m00:18:16
[2025-03-17T00:18:16.554+0000] {subprocess.py:106} INFO - [0m00:18:16  Concurrency: 4 threads (target='dev')
[2025-03-17T00:18:16.560+0000] {subprocess.py:106} INFO - [0m00:18:16
[2025-03-17T00:18:18.831+0000] {subprocess.py:106} INFO - [0m00:18:18  1 of 6 START sql view model public.clean_reviews ............................... [RUN]
[2025-03-17T00:18:18.847+0000] {subprocess.py:106} INFO - [0m00:18:18  2 of 6 START sql table model public.my_first_dbt_model ......................... [RUN]
[2025-03-17T00:18:18.857+0000] {subprocess.py:106} INFO - [0m00:18:18  3 of 6 START sql view model public.remove_duplicates ........................... [RUN]
[2025-03-17T00:18:18.911+0000] {subprocess.py:106} INFO - [0m00:18:18  4 of 6 START sql view model public.stg_clean_reviews ........................... [RUN]
[2025-03-17T00:18:20.658+0000] {subprocess.py:106} INFO - [0m00:18:20  4 of 6 ERROR creating sql view model public.stg_clean_reviews .................. [[31mERROR[0m in 1.61s]
[2025-03-17T00:18:20.727+0000] {subprocess.py:106} INFO - [0m00:18:20  5 of 6 SKIP relation public.dwh_model .......................................... [[33mSKIP[0m]
[2025-03-17T00:18:21.375+0000] {subprocess.py:106} INFO - [0m00:18:21  3 of 6 OK created sql view model public.remove_duplicates ...................... [[32mCREATE VIEW[0m in 2.49s]
[2025-03-17T00:18:21.427+0000] {subprocess.py:106} INFO - [0m00:18:21  1 of 6 OK created sql view model public.clean_reviews .......................... [[32mCREATE VIEW[0m in 2.56s]
[2025-03-17T00:18:21.431+0000] {subprocess.py:106} INFO - [0m00:18:21  2 of 6 OK created sql table model public.my_first_dbt_model .................... [[32mSELECT 2[0m in 2.56s]
[2025-03-17T00:18:21.442+0000] {subprocess.py:106} INFO - [0m00:18:21  6 of 6 START sql view model public.my_second_dbt_model ......................... [RUN]
[2025-03-17T00:18:21.963+0000] {subprocess.py:106} INFO - [0m00:18:21  6 of 6 OK created sql view model public.my_second_dbt_model .................... [[32mCREATE VIEW[0m in 0.51s]
[2025-03-17T00:18:22.162+0000] {subprocess.py:106} INFO - [0m00:18:22
[2025-03-17T00:18:22.164+0000] {subprocess.py:106} INFO - [0m00:18:22  Finished running 1 table model, 5 view models in 0 hours 0 minutes and 5.59 seconds (5.59s).
[2025-03-17T00:18:22.643+0000] {subprocess.py:106} INFO - [0m00:18:22
[2025-03-17T00:18:22.668+0000] {subprocess.py:106} INFO - [0m00:18:22  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[2025-03-17T00:18:22.676+0000] {subprocess.py:106} INFO - [0m00:18:22
[2025-03-17T00:18:22.678+0000] {subprocess.py:106} INFO - [0m00:18:22    Database Error in model stg_clean_reviews (models/stg_clean_reviews.sql)
[2025-03-17T00:18:22.678+0000] {subprocess.py:106} INFO -   syntax error at or near ";"
[2025-03-17T00:18:22.679+0000] {subprocess.py:106} INFO -   LINE 23: SELECT * FROM clean_data;
[2025-03-17T00:18:22.679+0000] {subprocess.py:106} INFO -                                    ^
[2025-03-17T00:18:22.680+0000] {subprocess.py:106} INFO -   compiled code at target/run/bank_reviews_project/models/stg_clean_reviews.sql
[2025-03-17T00:18:22.705+0000] {subprocess.py:106} INFO - [0m00:18:22
[2025-03-17T00:18:22.715+0000] {subprocess.py:106} INFO - [0m00:18:22  Done. PASS=4 WARN=0 ERROR=1 SKIP=1 TOTAL=6
[2025-03-17T00:18:26.452+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-17T00:18:26.916+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-17T00:18:27.007+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-17T00:18:27.008+0000] {logging_mixin.py:190} INFO - Task start:2025-03-17 00:17:57.359755+00:00 end:2025-03-17 00:18:26.971506+00:00 duration:29.611751
[2025-03-17T00:18:27.013+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_run> dag:<DAG: load_reviews_pipeline> dagrun:<DagRun load_reviews_pipeline @ 2024-04-02 00:00:00+00:00: scheduled__2024-04-02T00:00:00+00:00, state:running, queued_at: 2025-03-17 00:09:39.015984+00:00. externally triggered: False>
[2025-03-17T00:18:27.013+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-17T00:18:27.014+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=load_reviews_pipeline, task_id=dbt_run, run_id=scheduled__2024-04-02T00:00:00+00:00, execution_date=20240402T000000, start_date=20250317T001757, end_date=20250317T001826
[2025-03-17T00:18:27.846+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T00:18:27.889+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 169 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 251644)
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-17T00:18:28.341+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-17T00:18:28.562+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
