[2025-05-30T12:16:24.536+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T12:16:24.625+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.dbt_run_decisionnal manual__2025-05-29T22:45:07.665960+00:00 [queued]>
[2025-05-30T12:16:24.653+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.dbt_run_decisionnal manual__2025-05-29T22:45:07.665960+00:00 [queued]>
[2025-05-30T12:16:24.654+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-30T12:16:24.690+0100] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run_decisionnal> on 2025-05-29 22:45:07.665960+00:00
[2025-05-30T12:16:24.729+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'dbt_run_decisionnal', 'manual__2025-05-29T22:45:07.665960+00:00', '--job-id', '2578', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpe5g7mxgw']
[2025-05-30T12:16:24.710+0100] {standard_task_runner.py:72} INFO - Started process 21487 to run task
[2025-05-30T12:16:24.735+0100] {standard_task_runner.py:105} INFO - Job 2578: Subtask dbt_run_decisionnal
[2025-05-30T12:16:25.103+0100] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.dbt_run_decisionnal manual__2025-05-29T22:45:07.665960+00:00 [running]> on host DESKTOP-IM7V4RI.
[2025-05-30T12:16:25.449+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_decisionnal' AIRFLOW_CTX_EXECUTION_DATE='2025-05-29T22:45:07.665960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-29T22:45:07.665960+00:00'
[2025-05-30T12:16:25.452+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-30T12:16:25.453+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-30T12:16:25.453+0100] {logging_mixin.py:190} INFO - Current task name:dbt_run_decisionnal state:running start_date:2025-05-30 11:16:24.625799+00:00
[2025-05-30T12:16:25.454+0100] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-05-30T12:16:25.454+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-30T12:16:25.458+0100] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-30T12:16:25.460+0100] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/mohammed/.dbt/dbt_projects/bank_reviews_decisionnal && dbt run --full-refresh']
[2025-05-30T12:16:25.486+0100] {subprocess.py:99} INFO - Output:
[2025-05-30T12:16:31.508+0100] {subprocess.py:106} INFO - [0m11:16:31  Running with dbt=1.9.3
[2025-05-30T12:16:31.514+0100] {subprocess.py:106} INFO - [0m11:16:31  Encountered an error:
[2025-05-30T12:16:31.514+0100] {subprocess.py:106} INFO - Runtime Error
[2025-05-30T12:16:31.515+0100] {subprocess.py:106} INFO -   Could not find profile named 'bank_reviews_decisionnal'
[2025-05-30T12:16:32.774+0100] {subprocess.py:110} INFO - Command exited with return code 2
[2025-05-30T12:16:32.811+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-30T12:16:32.836+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-30T12:16:32.837+0100] {logging_mixin.py:190} INFO - Task start:2025-05-30 11:16:24.625799+00:00 end:2025-05-30 11:16:32.835468+00:00 duration:8.209669
[2025-05-30T12:16:32.837+0100] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dbt_run_decisionnal> dag:<DAG: bank_reviews_etl_and_analysis_pipeline> dagrun:<DagRun bank_reviews_etl_and_analysis_pipeline @ 2025-05-29 22:45:07.665960+00:00: manual__2025-05-29T22:45:07.665960+00:00, state:running, queued_at: 2025-05-29 22:45:08.602413+00:00. externally triggered: True>
[2025-05-30T12:16:32.838+0100] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-05-30T12:16:32.838+0100] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=dbt_run_decisionnal, run_id=manual__2025-05-29T22:45:07.665960+00:00, execution_date=20250529T224507, start_date=20250530T111624, end_date=20250530T111632
[2025-05-30T12:16:32.954+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-30T12:16:32.955+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 2578 for task dbt_run_decisionnal (Bash command failed. The command returned a non-zero exit code 2.; 21487)
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-30T12:16:32.993+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-30T12:16:33.052+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T12:16:33.056+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
