[2025-03-16T22:43:13.572+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T22:43:13.600+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_clean_reviews.topic_modeling manual__2025-03-16T22:37:56.104848+00:00 [queued]>
[2025-03-16T22:43:13.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_clean_reviews.topic_modeling manual__2025-03-16T22:37:56.104848+00:00 [queued]>
[2025-03-16T22:43:13.611+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-16T22:43:13.623+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): topic_modeling> on 2025-03-16 22:37:56.104848+00:00
[2025-03-16T22:43:13.628+0000] {standard_task_runner.py:72} INFO - Started process 164893 to run task
[2025-03-16T22:43:13.632+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'process_clean_reviews', 'topic_modeling', 'manual__2025-03-16T22:37:56.104848+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_Enrich_Data.py', '--cfg-path', '/tmp/tmpul8zk044']
[2025-03-16T22:43:13.633+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask topic_modeling
[2025-03-16T22:43:13.695+0000] {task_command.py:467} INFO - Running <TaskInstance: process_clean_reviews.topic_modeling manual__2025-03-16T22:37:56.104848+00:00 [running]> on host DESKTOP-IM7V4RI.
[2025-03-16T22:43:13.798+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_clean_reviews' AIRFLOW_CTX_TASK_ID='topic_modeling' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T22:37:56.104848+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T22:37:56.104848+00:00'
[2025-03-16T22:43:13.803+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T22:43:13.804+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T22:43:13.805+0000] {logging_mixin.py:190} INFO - Current task name:topic_modeling state:running start_date:2025-03-16 22:43:13.601275+00:00
[2025-03-16T22:43:13.805+0000] {logging_mixin.py:190} INFO - Dag name:process_clean_reviews and current dag run status:running
[2025-03-16T22:43:13.806+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T22:43:13.808+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-16T22:43:13.810+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/mohammed/airflow/scripts/topic_modeling.py']
[2025-03-16T22:43:13.825+0000] {subprocess.py:99} INFO - Output:
[2025-03-16T22:43:22.127+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-16T22:43:22.128+0000] {subprocess.py:106} INFO -   File "/home/mohammed/airflow/scripts/topic_modeling.py", line 58, in <module>
[2025-03-16T22:43:22.128+0000] {subprocess.py:106} INFO -     cur.execute("""
[2025-03-16T22:43:22.128+0000] {subprocess.py:106} INFO - psycopg2.errors.InvalidTextRepresentation: malformed array literal: "je, il, ne, pas, banque"
[2025-03-16T22:43:22.129+0000] {subprocess.py:106} INFO - LINE 3:         SET topics = 'je, il, ne, pas, banque' WHERE id = 48...
[2025-03-16T22:43:22.129+0000] {subprocess.py:106} INFO -                              ^
[2025-03-16T22:43:22.129+0000] {subprocess.py:106} INFO - DETAIL:  Array value must start with "{" or dimension information.
[2025-03-16T22:43:22.129+0000] {subprocess.py:106} INFO - 
[2025-03-16T22:43:22.556+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-16T22:43:22.577+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-16T22:43:22.581+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-16T22:43:22.582+0000] {logging_mixin.py:190} INFO - Task start:2025-03-16 22:43:13.601275+00:00 end:2025-03-16 22:43:22.581020+00:00 duration:8.979745
[2025-03-16T22:43:22.582+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): topic_modeling> dag:<DAG: process_clean_reviews> dagrun:<DagRun process_clean_reviews @ 2025-03-16 22:37:56.104848+00:00: manual__2025-03-16T22:37:56.104848+00:00, state:running, queued_at: 2025-03-16 22:37:56.178133+00:00. externally triggered: True>
[2025-03-16T22:43:22.582+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-16T22:43:22.582+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=process_clean_reviews, task_id=topic_modeling, run_id=manual__2025-03-16T22:37:56.104848+00:00, execution_date=20250316T223756, start_date=20250316T224313, end_date=20250316T224322
[2025-03-16T22:43:22.630+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T22:43:22.631+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 88 for task topic_modeling (Bash command failed. The command returned a non-zero exit code 1.; 164893)
Traceback (most recent call last):
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohammed/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-16T22:43:22.680+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T22:43:22.719+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T22:43:22.722+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
